---
{{- $ingressType := default "glb" .Values.ingress.type }}

{{- if eq $ingressType "glb" }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "microservice.name" . }}-ingress
  labels:
    app: {{ include "microservice.name" . }}
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: {{ default "static-app-ip" .Values.ingress.staticIP | quote }}
spec:
  rules:
    - host: {{ default "app.deployhub.com" .Values.ingress.host | quote }}
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: pdvd-backend
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "microservice.name" . }}
                port:
                  number: 8080
{{- else if eq $ingressType "kind" }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "microservice.name" . }}-ingress
  labels:
    app: {{ include "microservice.name" . }}
spec:
  ingressClassName: "traefik"
  rules:
    - http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: pdvd-backend
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "microservice.name" . }}
                port:
                  number: 8080
{{- end }}
---